#!/bin/bash

# Usage: operate <openrc> <tag> <ssh_key_path>
#                 $1      $2     $3

. $1
chmod +x operate_files/destroy.sh 
chmod +x operate_files/deploy.sh
# Generate key name
key_name="key_$2"

# Reassign $3 to the new key name

# source venv/bin/activate
get_current_instances() {
    openstack server list --format value -c Name | grep -E "^vm.*_$1$" | wc -l
}

# Function to get flavor ID based on criteria
get_flavor_id() {
    local FLAVOR_NAME=$(openstack flavor list -c ID -c RAM -c Disk -c VCPUs -f csv | awk -F ',' '$2 == 2048 && $3 == 20 && $4 == 2 {print $1}' | sed 's/"//g' | head -n 1)
    
    if [ -z "$FLAVOR_NAME" ]; then
        echo "No suitable flavor found."
        exit 1
    fi

    echo $FLAVOR_NAME
}
FLAVOR_NAME=$(get_flavor_id)

getSuitableImage() { 
    openstack image list --format json | \
    jq -r '.[] | select(.Name | test("(?i)ubuntu.*20")) | "\(.ID) \(.Name)"' | \
    while read -r image_id image_name; do
        echo $image_id
   done

}
 echo "Searching for suitable images..."
IMAGE_ID=$(getSuitableImage)


FLAVOR_NAME=$(get_flavor_id)

operation() {
    local new_number=$1
    local tag=$2
    local old_number=$(get_current_instances $tag) 
    local difference=$((new_number - old_number))
    local FLAVOR_NAME=$6
    
    echo "File changed! New number is: $new_number"
    echo "Current number of instances is: $old_number"
    echo "Difference is: $difference"
    echo "Tag is: $tag"
    echo "Key is $5"
    echo "Image id is $7"

    if [ $difference -lt 0 ]; then
        # Negative difference: destroy VMs
        for ((i=0; i<-difference; i++)); do
            echo "Destroying VM $((i+1)) of ${difference#-}"
            ./operate_files/destroy.sh "$3" "$4" "$5" 
        done
        cd operate_files
        bash install_software.sh "../storage/$5"
        cd ..
    elif [ $difference -gt 0 ]; then
        # Positive difference: deploy VMs
        for ((i=0; i<difference; i++)); do
            echo "Deploying VM $((i+1)) of $difference"
            ./operate_files/deploy.sh "$3" "$4" "$5" "$FLAVOR_NAME" "$7"
        done
        cd operate_files
        bash install_software.sh "../storage/$5"
        cd ..
    else
        echo "No change in VM count"
    fi
}

remove_stale_ips() {
    local ip_storage_path="./storage/ips"
    
    
    local live_ips=$(openstack server list -f json | jq -r '[.[].Networks | to_entries[] | .value[] | select(. | test("^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"))] | .[]')
    
    
    
    mapfile -t stored_ips < "$ip_storage_path"
    
    for stored_ip in "${stored_ips[@]}"; do
        if ! echo "$live_ips" | grep -q "^$stored_ip$"; then
            echo "Removing stale IP: $stored_ip"
            sed -i "/^$stored_ip$/d" "$ip_storage_path"
        fi
    done
}
monitor_file() {
    echo "Getting current instances... "
    local filename="$1"
    local last_modified=0
    local last_number=$(get_current_instances $3) 
    echo "Last number of instances is: $last_number"

    while true; do
    remove_stale_ips
        if [ -f "$filename" ]; then
            current_modified=$(stat -c %Y "$filename")
            if [ "$current_modified" != "$last_modified" ]; then
                content=$(cat "$filename" | tr -d '[:space:]')
                if [[ "$content" =~ ^[0-9]+$ ]]; then
                    if [ "$content" != "$last_number" ]; then
                        operation "$content" "$3" "$2" "$3" "$4" "$5" "$6"
                        last_number="$content"
                    fi
                else
                    echo "Invalid content in file: not a number"
                fi
                last_modified="$current_modified"
            fi
        else
            echo "File $filename not found. Waiting for it to be created..."
        fi
        current_instances=$(get_current_instances $3)
        if [ "$current_instances" != "$last_number" ]; then
            echo "Mismatch detected! Current instances: $current_instances, Expected: $last_number"
            operation "$last_number" "$3" "$2" "$3" "$4" "$5" "$6"
        fi
        sleep 30
    done
}

# Check if all required arguments are provided
if [ $# -ne 3 ]; then
    echo "Usage: $0 <openrc> <tag> <ssh_key>"
    exit 1
fi

monitor_file "servers.conf" "$1" "$2" "$key_name" "$FLAVOR_NAME" "$IMAGE_ID"
# openstack server list --format value -c Name | grep -E "^vm.*_r1$" | wc -l
